print ('L           J     M          M V           V')
print ('L           J     M M      M M  V         V')
print ('L           J     M  M   M   M   V       V')
print ('L           J     M    M     M    V     V')
print ('L     J     J     M          M     V   V')
print ('L      J    J     M          M      V V')
print ('LLLLL   JJJJ      M          M       V')