# print("Hello World!")
# print("What is your name?")
# Name=input()
# print("It is good to meet you " + Name)
# print("The length of your name is: " + str(len(Name)))
# print("How old are you?")
# Age = input()
# print("You will be " + str(int(Age) + 5) + " in 5 years.")

# print("□ Square and Rectangle Area Calculator □")
# print("Input the height of the figure:")
# height = int(input())
# print("Input the width of the figure:")
# width = int(input())
# print("The quadrilateral has an area of",  width*height, "square units.")

print("□ Perimeter of a Trapezoid Calculator □")
print("Input the length of the first side: ")
sidea = int(input())
print("Input the length of the second side: ")
sideb = int(input())
print("Input the length of the third side: ")
sidec = int(input())
print("Input the length of the fourth side: ")
sided = int(input())
print("The trapezoid has a perimeter of ", sidea+sideb+sidec+sided, "units")

def my_string(firstside, secondside, thirdside, fourthside):
    print(f"The trapezoid has a perimeter of", firstside + secondside + thirdside + fourthside, "units")
my_string(4,6,8,10)
